name: dev
channels:
    - conda-forge
dependencies:
    - python==3.6.*
    - opencv==3.4.*
    - numpy==1.16.2
    - pandas==0.23.0
    - matplotlib==2.1.1
    - jupyter==1.0.0
    - future==0.16.0
    - lxml==4.1.1
    - networkx==2.1
    - scikit-image==0.13.1
    - scipy==1.0.0
    - shapely==1.6.4
    - scikit-learn==0.19.1
    - pip:
        - visdom==0.1.7
        - bresenham==0.2
        - msgpack==0.5.6
        

